actions:
  files:
    format:
      extensions: [.ts]
      commands:
        - run: [(pnpm|yarn), exec, prettier, --write, $(files)]
        - run: [npm, exec, --, prettier, --write, $(files)]
        - run: [bun, x, prettier, --write, $(files)]
  final:
    install:
      dependencies:
        args:
          - dev: { (pnpm|yarn): [-D], bun: [--dev], npm: [--save-dev] }
          - { pinned: "$(name)@$(version)", any: "$(name)" }
      commands:
        - run: [(pnpm|bun|yarn), add]
        - run: [npm, install]
